/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WerewolfRouteImport } from './routes/werewolf'
import { Route as UndercoverRouteImport } from './routes/undercover'
import { Route as SpyfallRouteImport } from './routes/spyfall'
import { Route as BombPartyRouteImport } from './routes/bomb-party'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const WerewolfRoute = WerewolfRouteImport.update({
  id: '/werewolf',
  path: '/werewolf',
  getParentRoute: () => rootRouteImport,
} as any)
const UndercoverRoute = UndercoverRouteImport.update({
  id: '/undercover',
  path: '/undercover',
  getParentRoute: () => rootRouteImport,
} as any)
const SpyfallRoute = SpyfallRouteImport.update({
  id: '/spyfall',
  path: '/spyfall',
  getParentRoute: () => rootRouteImport,
} as any)
const BombPartyRoute = BombPartyRouteImport.update({
  id: '/bomb-party',
  path: '/bomb-party',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bomb-party': typeof BombPartyRoute
  '/spyfall': typeof SpyfallRoute
  '/undercover': typeof UndercoverRoute
  '/werewolf': typeof WerewolfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bomb-party': typeof BombPartyRoute
  '/spyfall': typeof SpyfallRoute
  '/undercover': typeof UndercoverRoute
  '/werewolf': typeof WerewolfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bomb-party': typeof BombPartyRoute
  '/spyfall': typeof SpyfallRoute
  '/undercover': typeof UndercoverRoute
  '/werewolf': typeof WerewolfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/bomb-party'
    | '/spyfall'
    | '/undercover'
    | '/werewolf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/bomb-party' | '/spyfall' | '/undercover' | '/werewolf'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/bomb-party'
    | '/spyfall'
    | '/undercover'
    | '/werewolf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BombPartyRoute: typeof BombPartyRoute
  SpyfallRoute: typeof SpyfallRoute
  UndercoverRoute: typeof UndercoverRoute
  WerewolfRoute: typeof WerewolfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/werewolf': {
      id: '/werewolf'
      path: '/werewolf'
      fullPath: '/werewolf'
      preLoaderRoute: typeof WerewolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undercover': {
      id: '/undercover'
      path: '/undercover'
      fullPath: '/undercover'
      preLoaderRoute: typeof UndercoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spyfall': {
      id: '/spyfall'
      path: '/spyfall'
      fullPath: '/spyfall'
      preLoaderRoute: typeof SpyfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bomb-party': {
      id: '/bomb-party'
      path: '/bomb-party'
      fullPath: '/bomb-party'
      preLoaderRoute: typeof BombPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BombPartyRoute: BombPartyRoute,
  SpyfallRoute: SpyfallRoute,
  UndercoverRoute: UndercoverRoute,
  WerewolfRoute: WerewolfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
